# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e20d7663f3af53fcfb0d14ec157030a3e5b3cb7a4852ef173b7dd66214cd9e233e41a93c63da1afb7abe7681bf8611790c0b8f75090853e811a4be7b6c02402

test:
  secret_key_base: 835f702f5850ce1331ad6583fec2ccb978210d0550857b7cf3262ec69581686ad2b8b1a8945a6f88208582a384249fec66383865cb51eca49fdf3ebdee0de7b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
